### ISSUE TITLE
Question: Change color of inactive dots?

### ISSUE THREAD

**Issue by Gene-Dana** [Pyozer/dots_indicator#11]
Hi there ! Just wondering if there is functionality to change the color of the inactive dots. I did not see it explicitly and it's very possible I overlooked something!

**Comment by Pyozer** [comment]
Hi, yes you can customize colors of inactive dots.
You have to set `color` property in your `DotsDecorator` object.

Like this:
```dart
const decorator = DotsDecorator(
      color: Colors.green
      activeColor: Colors.red,
      activeSize: Size.square(50.0),
      activeShape: RoundedRectangleBorder(),
    );
```
