### ISSUE TITLE
Active Color cannot be set from Theme.of(context).primaryColor due to invalid constant value. Please fix this.

### ISSUE THREAD

**Issue by ankitkarna99** [Pyozer/dots_indicator#12]
Letting you know because, we don't like to use same color code again and again.

**Comment by Pyozer** [comment]
Hi, so sorry for delay :/
i don't really understand/see the issue, obviously, you cannot use `Theme.of(context).primaryColor` and set the `decorator` param with a const, like `decorator: const DotsDecorator(color: Theme.of(context).primaryColor)`.

I close the issue assuming it's too old, but if you want to made a new issue about this, no problem.
