### ISSUE TITLE
Dynamic sized unActive or Active Dots

### ISSUE THREAD

**Issue by miguelflores1993** [Pyozer/dots_indicator#18]
Good morning everyone.
I want to manage that the points are dynamic that the activated and the not activated, are long according to the number of pages it has, is it possible?
I attach a picture[](url)

https://ibb.co/wM7Nysv

**Comment by Pyozer** [comment]
Hi, sorry for delay :/ 
Thank you for the idea, but I will not adding this sorry, except if you made a PR.
But I think it's already possible using dots custom size, shape, etc..
