### ISSUE TITLE
Provide an Example Code,when creating a plugin

### ISSUE THREAD

**Issue by ghost** [Pyozer/dots_indicator#2]
not all the case super coders are using ur plugins,consider newbies too,pls attactch a simple example

**Comment by Pyozer** [comment]
I already provide some code example in the readme, but if you want I will update it, to provide you a full code example ;)

**Comment by ghost** [comment]
not needed bro,i used onpagechanged(){}

thanks

**Comment by Pyozer** [comment]
Oh ok, sorry for responding late ;)
