### ISSUE TITLE
Latest release is patch version bump but breaking change

### ISSUE THREAD

**Issue by thomas-stockx** [Pyozer/dots_indicator#25]
Latest change (position to int) is a breaking change and as such can break other (library) packages which depend on dots_inidicator.

Would it be possible to pull the latest version and re-release it as a breaking change (3.0.0)?

**Comment by Pyozer** [comment]
Hi, you're right, I've just published a 2.1.2 with the revert and a 3.0.0 with the breaking change.

**Comment by ghenry** [comment]
Apologies. I did see that in the PR but forgot to act on it.

**Comment by jeanlucthumm** [comment]
Previously you could control the animation between dots since it was double. This paired well with [Carousel Slider](https://pub.dev/packages/carousel_slider) `onScrolled` for better animation. How are you supposed to do that now?

**Comment by Pyozer** [comment]
@jeanlucthumm Yes, version 3.0.0 was a mistake... but I don't have much time to maintain my packages, so I never changed that...
You can use version 2.1.2 to have a double position.
I will try to find time to update my packages.

I think I will release a 4.0.0 with a double position (like 2.1.2) and some other changes.
