### ISSUE TITLE
Dots direction

### ISSUE THREAD

**Issue by ashikdnd** [Pyozer/dots_indicator#5]
Hey Thanks for the awesome package. This made my job very easy. However the direction property is missing. I would like to use a vertical indicator rather horizontal. Do you have plans to upgrade the plugin anytime soon?

**Comment by Pyozer** [comment]
Hi :)

Oh yeah it's a great idea to have a direction property !
I will add it soon ;)

Thanks for your feedback

**Comment by ashikdnd** [comment]
That's cool. I will use the horizontal dots until the direction property is added.

**Comment by Pyozer** [comment]
I publish on pub the `v1.0.0` 🎉

This update provide two new property:
- `axis`: `Axis.horizontal` or `Axis.vertical`
- `reversed`: `true` or `false`

Also, I add an example app on package ;)

**Comment by ashikdnd** [comment]
Thank you :) This feature is really beneficial.
