### ISSUE TITLE
Delayed transition

### ISSUE THREAD

**Issue by softower** [Pyozer/dots_indicator#6]
I have a Pageview widget setup along with dots indicator. When the page changes the "position" of the dot also changes. So the dot transition happens immediately even before the page transition completes. A "delay" property would be great to keep both dot and the page transitions in sync.

**Comment by Pyozer** [comment]
Hi, I'm so sorry for the very very late reply.

Hope you have found a solution.
I think you update dots position too early. You can wrap your PageView with a `NotificationListener<ScrollNotification>`, with this, you will be able to have a callback on PageView position changes, and update Dots position in same time (both positions are double).
You can check source code of my other package [introduction_screen](https://github.com/Pyozer/introduction_screen).

I close this issue, if you have any other questions,  re-open it ;)
