### ISSUE TITLE
Overflow with flutter web

### ISSUE THREAD

**Issue by fvisticot** [Pyozer/dots_indicator#9]
The plugin is working perfectly for the mobile app (Android / iOS)

When I try to use this plugin with flutter web it works fine except when I try to resize the window.
When I resize the window, more points are added to the dots indicator and an overflow appear on the right.

Error: 

The relevant error-causing widget was: 
  Row org-dartlang-app:///packages/dots_indicator/src/dots_indicator.dart:61:11
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

**Comment by Pyozer** [comment]
Hi, oh old issue, so sorry for the delay..

I close it since it's very old, if you want to reopen it, no problem.
